# Generated by Django 4.2.3 on 2023-08-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('componente', models.CharField(choices=[('procesador', 'Procesador'), ('placa_video', 'Placa de Video'), ('motherboard', 'Placa Madre'), ('gabinete', 'Gabinete'), ('ram', 'RAM'), ('almacenamiento', 'Almacenamiento'), ('otro', 'Otro')], default='procesador', max_length=40)),
                ('titulo', models.CharField(max_length=60)),
                ('marca', models.CharField(max_length=40)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagenComponente', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
                ('year', models.CharField(max_length=40)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fechaPublicacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fechaPublicacion'],
            },
        ),
    ]
