# Generated by Django 4.2.3 on 2023-08-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainWeb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('comentario', models.CharField(max_length=250)),
                ('fechaComentario', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fechaComentario'],
            },
        ),
    ]
