# Generated by Django 4.2.3 on 2023-08-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainWeb', '0002_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provincia', models.CharField(choices=[('buenos_aires', 'Buenos Aires'), ('catamarca', 'Catamarca'), ('chaco', 'Chaco'), ('chubut', 'Chubut'), ('cordoba', 'Córdoba'), ('corrientes', 'Corrientes'), ('entre_rios', 'Entre Rios'), ('formosa', 'Formosa'), ('jujuy', 'Jujuy'), ('la_pampa', 'La Pampa'), ('la_rioja', 'La Rioja'), ('mendoza', 'Mendoza'), ('neuquen', 'Neuquén'), ('rio_negro', 'Rio Negro'), ('salta', 'Salta'), ('san_juan', 'San Juan'), ('santa_luis', 'Santa Luis'), ('santa_cruz', 'Santa Cruz'), ('santa_fe', 'Santa Fe'), ('santiago_del_estero', 'Santiago del Estero'), ('tierra_de_fuego', 'Tierra de Fuego'), ('tucuman', 'Tucumán')], default='buenos_aires', max_length=30)),
                ('nombre', models.CharField(max_length=60)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
