# Generated by Django 4.2.3 on 2023-08-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainWeb', '0004_alter_sucursal_options_sucursal_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componente',
            name='componente',
            field=models.CharField(choices=[('procesador', 'Procesador'), ('placa_video', 'Placa de Video'), ('motherboard', 'Placa Madre'), ('gabinete', 'Gabinete'), ('ram', 'RAM'), ('almacenamiento', 'Almacenamiento'), ('otro', 'Otro')], default='procesador', max_length=20),
        ),
        migrations.AlterField(
            model_name='componente',
            name='imagenComponente',
            field=models.ImageField(blank=True, null=True, upload_to='D:/CODERHOUSE Python/Proyecto Final/PCfinder/imagenes/'),
        ),
    ]
