# Generated by Django 4.2.3 on 2023-08-27 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainWeb', '0005_alter_componente_componente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componente',
            name='imagenComponente',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
    ]
