# Generated by Django 4.2.3 on 2023-08-28 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainWeb', '0009_alter_componente_imagencomponente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componente',
            name='imagenComponente',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
    ]
