# Generated by Django 4.2.3 on 2023-08-29 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainWeb', '0011_alter_componente_imagencomponente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='componenteAsociado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='MainWeb.componente'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='imagenComponente',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
    ]
