# Generated by Django 4.2.3 on 2023-09-01 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainWeb', '0012_cliente_componenteasociado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componente',
            name='componente',
            field=models.CharField(choices=[('procesador', 'Procesador'), ('placa_video', 'Placa de Video'), ('motherboard', 'Placa Madre'), ('gabinete', 'Gabinete'), ('ram', 'RAM'), ('otro', 'Otro')], default='procesador', max_length=20),
        ),
    ]
