# Generated by Django 4.2.3 on 2023-09-01 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainWeb', '0013_alter_componente_componente'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='mapa',
            field=models.CharField(default='', max_length=500),
        ),
    ]
