# Generated by Django 4.2.3 on 2023-09-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainWeb', '0014_sucursal_mapa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='mapa',
            field=models.SlugField(default='', max_length=500),
        ),
    ]
