# Generated by Django 4.2.3 on 2023-09-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainWeb', '0015_alter_sucursal_mapa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='mapa',
            field=models.URLField(default='', max_length=500),
        ),
    ]
